{% set name = "pymc3-hmm" %}
{% set version = "0.2.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 424bf7c382fe94947ef25cf79b44aaf79c950e71e1500f2340b3554cd572621c

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - numpy >=1.15.0
    - scipy >=1.2.0
    - pymc3 >=3.11.0
    - theano-pymc >=1.1.0
    - mkl-service

test:
  imports:
    - pymc3_hmm

about:
  home: https://github.com/AmpersandTV/pymc3-hmm
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Hidden Markov models in PyMC3
  description: |
    Fully implemented PyMC3 Distribution classes for HMM state sequences (DiscreteMarkovChain) and mixtures that are driven by them (SwitchingProcess).
    A forward-filtering backward-sampling (FFBS) implementation (FFBSStep) that works with NUTS—or any other PyMC3 sampler.
    A conjugate Dirichlet transition matrix sampler (TransMatConjugateStep).
    Support for time-varying transition matrices in the FFBS sampler and all the relevant Distribution classes.
  doc_url: https://nbviewer.jupyter.org/github/AmpersandTV/pymc3-hmm/tree/main/examples/
  dev_url: https://github.com/AmpersandTV/pymc3-hmm

extra:
  recipe-maintainers:
    - brandonwillard
    - dgerlanc
    - fanshi118
